config:
 partial_parse: true
jaffle_shop:
 target: fabric-dev
 outputs:
  fabric-dev:
   authentication: CLI
   database: dbttry
   driver: ODBC Driver 18 for SQL Server
   host: u36vj6cpdbae7jpcqospreskcu-hydt7ofhz2xethb7mmdjpenos4.datawarehouse.fabric.microsoft.com
   schema: dbo
   threads: 4
   type: fabric